TravelAgency/TravelAgency.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelAgency.WebUI.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }

    }
}

TravelAgency/TravelAgency.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Domain.Abstract;
using TravelAgency.Domain.Entities;
using TravelAgency.Domain.Concrete;
using System.Data.Entity.Validation;

namespace TravelAgency.WebUI.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        private ITourRepository repository;
        private ISavior savior;
        public HomeController(ITourRepository repo, ISavior save)
        {
            repository = repo;
            savior = save;
        }
        public ViewResult List()
        {
            return View(repository.Tours);
        }
        [HttpGet]
        public ActionResult SignUp()
        {
            return View(new Client());
        }
        [HttpPost]
        public ActionResult SignUp(Client client)
        {
            client.DOB = Convert.ToDateTime(client.BirthdateDay + "." + client.BirthdateMonth + "." + client.BirthdateYear);
            //client.DOB = Convert.ToDateTime(client.BirthdateDaySelectList.First(x => x.Selected == true).Value + "."+client.BirthdateMonthSelectList.First(x => x.Selected == true).Value + "." + client.BirthdateYearSelectList.First(x => x.Selected == true).Value);
            if (!savior.IsLoginUnique(client))
            {
                ModelState.AddModelError("Login", "Пользователь с таким логином уже зарегистрирован");
                //ViewBag.NotUniqueLogin = "Такой логин уже существует";
                return View(client);
            }    
            if (ModelState.IsValid)
            {
                savior.AddClientToDb(client);
                //savior.SaveChanges();
            }
            return View(client);
        }
        public ActionResult Index()
        {
            return View();
        }
       
    }
}

TravelAgency/TravelAgency.WebUI/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Domain.Abstract;
using TravelAgency.Domain.Entities;

namespace TravelAgency.WebUI.Controllers
{
    public class HotelController : Controller
    {
        //
        // GET: /Hotel/
        IHotelRepository repository;
        public HotelController(IHotelRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Hotels);
        }
        [HttpGet]
        public ViewResult Edit(int id)
        {
            Hotel hotel = repository.Hotels.FirstOrDefault(t => t.Id == id);
            hotel.SelectCity = repository.SelectCity;
            hotel.SelectAllocationType = repository.SelectAllocationType;
            return View(hotel);
        }
        [HttpPost]
        public ActionResult Edit(Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateCreate(hotel);
                TempData["message"] = string.Format("Изменения в отеле \"{0}\" были сохранены", hotel.Name);
                return RedirectToAction("Index");
            }
            hotel.SelectCity = repository.SelectCity;
            hotel.SelectAllocationType = repository.SelectAllocationType;
            return View(hotel);
        }
        public ViewResult Create(Hotel hotel)
        {
            Hotel tour = new Hotel();
            hotel.SelectCity = repository.SelectCity;
            hotel.SelectAllocationType = repository.SelectAllocationType;
            return View("Edit", hotel);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Hotel deletedHotel = repository.Delete(id);
            if (deletedHotel != null)
            {
                TempData["message"] = string.Format("Отель \"{0}\" был удален", deletedHotel.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

TravelAgency/TravelAgency.WebUI/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Domain.Abstract;
using TravelAgency.Domain.Entities;

namespace TravelAgency.WebUI.Controllers
{
    public class TourController : Controller
    {
        //
        // GET: /Admin/
        ITourRepository repository;
        public TourController(ITourRepository repo)
        {
            repository = repo;
        }
        
        public ViewResult Index()
        {
            return View(repository.Tours);
        }
        [HttpGet]
        public ViewResult Edit(int id)
        {
            Tour tour = repository.Tours.FirstOrDefault(t => t.Id == id);
            repository.Select(tour);
            return View(tour);
        }
        [HttpPost]
        public ActionResult Edit(Tour tour)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateCreateTour(tour);
                TempData["message"] = string.Format("Изменения в туре \"{0}\" были сохранены", tour.Id);
                return RedirectToAction("Index");
            }
            repository.Select(tour);
            return View(tour);
        }
        public ViewResult Create()
        {
            Tour tour = new Tour();
            repository.Select(tour);
            return View("Edit", tour);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Tour deletedTour = repository.DeleteTour(id);
            if (deletedTour != null)
            {
                TempData["message"] = string.Format("Тур с ID \"{0}\" был удален", id);
            }
            return RedirectToAction("Index");
        }
        
    }
}

TravelAgency/TravelAgency.WebUI/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="panel">
    <div class="panel-heading">
        <h2>Личный кабинет</h2>
    </div>
    <div class="panel-body">
        <div>
            @using (@Html.BeginForm("Index", "Hotel"))
            {
                <input type="submit" class="btn btn-default btn-xs" value="Отели" />
            }
        </div>
        <div>
            @using (@Html.BeginForm("Index", "Tour"))
            {
                <input type="submit" class="btn btn-default btn-xs" value="Туры" />
            }
        </div>
    </div>

</div>

TravelAgency/TravelAgency.WebUI/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/cover.css" rel="stylesheet" />
    @*<style>
        body{
            background-image: url(../../Content/пальма2.jpg);
        }
    </style>*@
</head>
<body>
    <div class="site-wrapper">

        <div class="site-wrapper-inner">

            <div class="cover-container">

                <div class="masthead clearfix">
                    <div class="inner">
                        <h3 class="masthead-brand">Village Travel</h3>
                        <nav>
                            <ul class="nav masthead-nav">
                                <li class="active">@Html.ActionLink("Home","Index")</li>
                                <li class="active">@Html.ActionLink("Sign Up", "SignUp")</li>
                                <li class="active">@Html.ActionLink("Sig In", "SignIn")</li>
                                <li class="active">@Html.ActionLink("Tours", "List")</li>
                            </ul>
                        </nav>
                    </div>
                </div>

                <div class="inner cover">
                    <h1 class="cover-heading">Travel Agency</h1>
                    <p class="lead" >At Village Travel, we have consultants with an average of 20 years experience and a passion for travel available who will work out the details and create unforgettable vacations.

We will work with you to plan a worry free adventure that meets your travel needs, expectations and budget. When you plan your vacation with us we are there throughout the entire process.  This means making ourselves available to you before, during and after travel.

We plan river and ocean cruises, romantic honeymoon packages to sunny destinations, family, adventure and wellness travel along with international and domestic customized itineraries.</p>
                    
                    <div class="btn btn-lg btn-default">
                        <a>@Html.ActionLink("Go!", "AutorizationForm")</a>
                    </div>
             </div>

            </div>

        </div>

    </div>
</body>
</html>

TravelAgency/TravelAgency.WebUI/Views/Home/List.cshtml
@using TravelAgency.Domain.Entities
@model IEnumerable<Tour>

@{
    ViewBag.Title = "Туры";
}

@foreach (var p in @Model)
{
    <div>
        <h3>@p.StartDate.Date</h3>
        <h3>@p.EndDate.Date</h3>
        <h3>@p.Description</h3>
        <h3>@p.TourType.Type</h3>
        <h3>@p.FoodType1.FoodType1</h3>
        <h3>@p.Hotel.Name</h3>
        <h3>@p.Hotel.City.Name</h3>
    </div>
}

TravelAgency/TravelAgency.WebUI/Views/Home/SignUp.cshtml
@model TravelAgency.Domain.Entities.Client

@{
    ViewBag.Title = "SignUp";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RSVPForm</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    @*<style>
        body{
            background-image: url(../../Content/пальма3jpg.jpg)
        }
    </style>*@
</head>
<body>
    <div class="panel-success">
        <div class="panel-heading text-center">
            <h4>Регистрация</h4>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            { 
                @Html.ValidationSummary()
                <div class="validation-summary-errors">
                    @ViewBag.NotUniqueLogin
                </div>
                <div class="form-group">
                    <label>Ваше имя:</label>
                    @Html.TextBoxFor(x => x.FullName, new { @class = "form-control" })
                    @*@Html.ValidationMessageFor(x => x.FullName)*@
                </div>
                <div class="form-group">
                    <label>Ваша дата рождения:</label>
                    @Html.DropDownListFor(x => x.BirthdateDay, Model.BirthdateDaySelectList, new { @class = "form-control"})
                    @Html.DropDownListFor(x => x.BirthdateMonth, Model.BirthdateMonthSelectList, new { @class = "form-control" })
                    @Html.DropDownListFor(x => x.BirthdateYear, Model.BirthdateYearSelectList, new { @class = "form-control" })
                    @*@Html.TextBoxFor(x => x.DOB, new { @class = "form-control" })*@
                   @* @Html.ValidationMessageFor(x => x.DOB)*@
                </div>
                <div class="form-group">
                    <label>Ваш паспорт:</label>
                    @Html.TextBoxFor(x => x.Passport, new { @class = "form-control" })
                    @*@Html.ValidationMessageFor(x => x.Passport)*@
                </div>
                <div class="form-group">
                    <label>Ваш телефон:</label>
                    @Html.TextBoxFor(x => x.PhoneNum, new { @class = "form-control" })
                    @*@Html.ValidationMessageFor(x => x.PhoneNum)*@
                </div>
                <div class="form-group">
                    <label>Ваш адрес:</label>
                    @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
                   @* @Html.ValidationMessageFor(x => x.Address)*@
                </div>
                <div class="form-group">
                    <label>Придумайте логин:</label>
                    @Html.TextBoxFor(x => x.User.Login, new { @class = "form-control" })
                   @* @Html.ValidationMessageFor(x => x.User.Login)*@
                </div>
                <div class="form-group">
                    <label>Придумайте пароль:</label>
                    @Html.PasswordFor(x => x.User.Password, new { @class = "form-control" })
                   @* @Html.ValidationMessageFor(x => x.User.Password)*@
                </div>
                <div class="text-center">
                    <input type="submit" value="Отправить" class="btn-success" />
                </div>
            }
        </div>
    </div>

</body>
</html>

TravelAgency/TravelAgency.WebUI/Views/Hotel/Edit.cshtml
@model TravelAgency.Domain.Entities.Hotel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel">
    <div class="panel-heading">
        <h2>Edit</h2>
    </div>
    @using (Html.BeginForm("Edit", "Hotel"))
    {
        <div class="panel-body">
            <div class="form-group">
                <label>Название</label>
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Количество звезд</label>
                @Html.TextBoxFor(x => x.Stars, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Цена за ночь</label>
                @Html.TextBoxFor(x => x.NightPrice, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Город расположения</label>
                @Html.DropDownListFor(x => x.CityId, Model.SelectCity, new { @class = "form-control" })
            </div>
            @*<div class="form-group">
                <label>Отель</label>
                @Html.DropDownListFor(x => x.HotelId, Model.SelectHotel, new { @class = "form-control" })
            </div>*@


        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new { @class = "btn brn-default" })

        </div>
    }
</div>
<

TravelAgency/TravelAgency.WebUI/Views/Hotel/Index.cshtml
@model IEnumerable<TravelAgency.Domain.Entities.Hotel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Список отелей</h2>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">
                    Название
                </th>
                <th class="text-right">
                    Количество звезд
                </th>
                <th class="text-right">
                   Город расположения
                </th>
                <th class="text-right">
                    Цена за ночь
                </th>
                <th class="text-right">Действия</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @Html.ActionLink(item.Name, "Edit", new { id = item.Id })
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Stars)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.City.Name)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.NightPrice)
                    </td>
                    <td class="text-center">
                        @using (@Html.BeginForm("Delete", "Hotel"))
                        {
                            @Html.Hidden("ID", item.Id)
                            <input type="submit" class="btn btn-default btn-xs" value="Удалить" />
                        }
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                    </td>
                </tr>
            }

        </table>

    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить отель", "Create", null, new { @class = "btn btn-default" })
    </div>
    <div class="panel-footer">
        @using (@Html.BeginForm("Index", "Admin"))
        {
            <input type="submit" class="btn btn-default btn-xs" value="Вернуться в личный кабинет" />
        }
    </div>
</div>

TravelAgency/TravelAgency.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
</head>
<body>
    <div>
        @if(TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

TravelAgency/TravelAgency.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

TravelAgency/TravelAgency.WebUI/Views/Tour/Edit.cshtml
@model TravelAgency.Domain.Entities.Tour

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel">
    <div class="panel-heading">
        <h2>Редактирование тура c ID="@Model.Id"</h2>
    </div>
    @using (Html.BeginForm("Edit", "Tour"))
    {
        <div class="panel-body">
            <div class="form-group">
                <label>Дата начала</label>
                @Html.TextBoxFor(x => x.StartDate, new { @class = "form-control"})
            </div>
            <div class="form-group">
                <label>Дата конца</label>
                @Html.TextBoxFor(x => x.EndDate, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Описание</label>
                @Html.TextAreaFor(x => x.Description, new { @class = "form-control", rows = 5})
            </div>
           
            <div class="form-group">
                <label>Тип тура</label>
                @Html.DropDownListFor(x => x.Type, Model.SelectType, new { @class = "form-control"})
            </div>
            <div class="form-group">
                <label>Тип питания</label>
                @Html.DropDownListFor(x => x.FoodType, Model.SelectFoodType, new { @class = "form-control"})
            </div>
            <div class="form-group">
                <label>Отель</label>
                @Html.DropDownListFor(x => x.HotelId, Model.SelectHotel, new { @class = "form-control"})
            </div>
            

        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary"/>
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new { @class = "btn brn-default" })

        </div>
    }
    </div>

TravelAgency/TravelAgency.WebUI/Views/Tour/Index.cshtml
@model IEnumerable<TravelAgency.Domain.Entities.Tour>

@{
    ViewBag.Title = "Админ панель: список туров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Список туров</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th class="text-right">Город</th>
                <th class="text-right">Дата начала</th>
                <th class="text-right">Дата конца</th>
                <th class="text-right">Тип</th>
                <th class="text-right">Тип питания</th>
                <th class="text-right">Отель</th>
                <th class="text-right">Описание</th>
                <th class="text-center">Действия</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @Html.ActionLink(item.Id.ToString(), "Edit", new { id = item.Id })
                        @*@Html.DisplayFor(modelItem => item.Id)*@
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Hotel.City.Name)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.TourType.Type)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.FoodType1.FoodType1)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Hotel.Name)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td class="text-center">
                        @using (@Html.BeginForm("Delete","Tour"))
                        {
                            @Html.Hidden("ID", item.Id)
                            <input type="submit" class="btn btn-default btn-xs" value="Удалить"/>
                        }
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                    </td>
                </tr>
            }
        </table> 
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить тур", "Create", null, new { @class = "btn btn-default"})
    </div>
    <div class="panel-footer">
        @using (@Html.BeginForm("Index", "Admin"))
        {
            <input type="submit" class="btn btn-default btn-xs" value="Вернуться в личный кабинет" />
        }
    </div>
</div>